# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json

name: Check for yamlfmt updates

on:
  workflow_dispatch:
  schedule:
    - cron: "38 4 * * 6"  # every Saturday at 04:38 UTC   <https://crontab.guru/#38_4_*_*_6>

permissions:
  contents: write
  pull-requests: write

env:
  UPDATE_BRANCH_NAME: "autoupdate"

jobs:

  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: true

      - uses: pcrockett/setup-just@096177f0c832d972bdf47b0fac0e8b9c0eb49326  # v0.1.2

      - run: |
          if ! git switch --create "${UPDATE_BRANCH_NAME}" "origin/${UPDATE_BRANCH_NAME}"; then
            git switch --create "${UPDATE_BRANCH_NAME}"
          fi

          just update

          new_version="$(yq eval '.inputs.version.default' action.yml)"
          if [ "$(git status --porcelain)" != "" ]; then
            echo "Found update: ${new_version}"
            git add .
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git commit -m "Update to version ${new_version}"
            git push origin "${UPDATE_BRANCH_NAME}"
          fi

          pr_title="Update to version ${new_version}"
          if [ "$(gh pr view --json state --jq .state 2>/dev/null)" == "OPEN" ]; then
            echo "Updating existing PR..."
            gh pr edit --title "${pr_title}"
          elif [ "$(git diff "main..${UPDATE_BRANCH_NAME}")" != "" ]; then
            echo "Creating new PR..."
            gh pr create --title "${pr_title}" --body ""
          else
            echo "Already current!"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
